df <- read.csv("c:\\Users\\pasha\\OneDrive\\Рабочий стол\\R\\dz7\\ДЗ2_vgsales.csv")
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
library(plotly)
library(leaflet)
library(rpivotTable)
library(DT)
print(head(df))